default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  timeout: <%= ENV.fetch("RAILS_MAX_THREADS") { 5000 } %>

development:
  <<: *default
  adapter: postgresql

test:
  <<: *default
  adapter: postgresql

production:
  <<: *default
  database: db/production.sqlite3